spring.application.name=INTEGRATION-SERVICE

server.port=8004


# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Eureka Instance
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


# Compatibility
spring.cloud.compatibility-verifier.enabled=false


# Geoapify API Key (for Geocoding + Routing)
geoapify.api.key=38030a2fe3b0435e80e326564ca7d380

# OpenChargeMap (for charging station discovery)
opencharge.api.key=32e1d678-2c86-4ad2-9e42-7b653a8ffdc9
